//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOdevim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseOdevimEntities : DbContext
    {
        public DatabaseOdevimEntities()
            : base("name=DatabaseOdevimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public DbSet<PROJECT> PROJECT { get; set; }
        public DbSet<DEPENDENT> DEPENDENT { get; set; }
        public DbSet<DEPT_LOCATIONS> DEPT_LOCATIONS { get; set; }
        public DbSet<WORKS_ON> WORKS_ON { get; set; }
    }
}
