//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOdevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.PROJECT = new HashSet<PROJECT>();
        }
    
        public string Dname { get; set; }
        public int Dnumber { get; set; }
        public int Mgr_ssn { get; set; }
        public Nullable<System.DateTime> Mgr_start_date { get; set; }
    
        public virtual ICollection<PROJECT> PROJECT { get; set; }
    }
}
