//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOdevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPENDENT
    {
        public int Essn { get; set; }
        public string Dependent_name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Bdate { get; set; }
        public string Relationship { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
