//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOdevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT_LOCATIONS
    {
        public int Dnumber { get; set; }
        public string Dlocation { get; set; }
    }
}
