//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOdevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.EMPLOYEE1 = new HashSet<EMPLOYEE>();
            this.WORKS_ON = new HashSet<WORKS_ON>();
        }
    
        public string Fname { get; set; }
        public string Minit { get; set; }
        public string Lname { get; set; }
        public int Ssn { get; set; }
        public Nullable<System.DateTime> Bdate { get; set; }
        public string Adress { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Super_ssn { get; set; }
        public int Dno { get; set; }
    
        public virtual DEPENDENT DEPENDENT { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEE1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE2 { get; set; }
        public virtual ICollection<WORKS_ON> WORKS_ON { get; set; }
    }
}
