//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOdevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public string Pname { get; set; }
        public int Pnumber { get; set; }
        public string Plocation { get; set; }
        public int Dnum { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
