//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOdevim
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKS_ON
    {
        public int Essn { get; set; }
        public int Pno { get; set; }
        public Nullable<double> Hours { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
